name: SkyblockFOSS
version: ${project.version}
main: com.skyblock.SkyblockPlugin
api-version: '1.20'
description: A comprehensive Hypixel Skyblock recreation plugin
author: SkyblockFOSS Team
website: https://github.com/skyblock-foss

softdepend:
  - Vault
  - PlaceholderAPI

commands:
  skyblock:
    description: Open the main Skyblock menu
    aliases: [sb, sbmenu]
    permission: skyblock.menu

  skills:
    description: View your skills
    permission: skyblock.skills

  collections:
    description: View your collections
    aliases: [col, collection]
    permission: skyblock.collections

  profile:
    description: Manage your profiles
    aliases: [profiles]
    permission: skyblock.profile

  sbadmin:
    description: Admin commands for Skyblock
    aliases: [sba]
    permission: skyblock.admin

  coins:
    description: View or manage coins
    permission: skyblock.coins

  shop:
    description: Open the shop menu
    permission: skyblock.shop

  # Phase 1.5 Commands
  island:
    description: Manage your private island
    aliases: [is]
    permission: skyblock.island

  visit:
    description: Visit another player's island
    permission: skyblock.visit

  hub:
    description: Teleport to the hub world
    aliases: [spawn, lobby]
    permission: skyblock.hub

  coopadd:
    description: Invite a player to your co-op island
    permission: skyblock.coop

  coopkick:
    description: Start a vote to kick a co-op member
    permission: skyblock.coop

  coopview:
    description: View your co-op members
    permission: skyblock.coop

  coopsalvage:
    description: Salvage your co-op (owner only)
    permission: skyblock.coop

  coopleave:
    description: Leave your co-op island
    permission: skyblock.coop

  # Phase 2 Commands
  pets:
    description: View and manage your pets
    aliases: [pet]
    permission: skyblock.pets

permissions:
  skyblock.*:
    description: All Skyblock permissions
    default: op
    children:
      skyblock.menu: true
      skyblock.skills: true
      skyblock.collections: true
      skyblock.profile: true
      skyblock.coins: true
      skyblock.shop: true
      skyblock.admin: true
      skyblock.admin.items: true
      skyblock.admin.players: true
      skyblock.admin.economy: true
      skyblock.admin.reload: true
      # Phase 1.5
      skyblock.island: true
      skyblock.visit: true
      skyblock.hub: true
      skyblock.coop: true
      skyblock.garden: true
      # Phase 2
      skyblock.pets: true

  skyblock.menu:
    description: Access the Skyblock menu
    default: true

  skyblock.skills:
    description: View skills
    default: true

  skyblock.collections:
    description: View collections
    default: true

  skyblock.profile:
    description: Manage profiles
    default: true

  skyblock.coins:
    description: View coins
    default: true

  skyblock.shop:
    description: Access shops
    default: true

  skyblock.admin:
    description: Access admin features
    default: op

  skyblock.admin.items:
    description: Spawn items
    default: op

  skyblock.admin.players:
    description: Manage players
    default: op

  skyblock.admin.economy:
    description: Manage economy
    default: op

  skyblock.admin.reload:
    description: Reload configuration
    default: op

  # Phase 1.5 Permissions
  skyblock.island:
    description: Access island commands
    default: true

  skyblock.visit:
    description: Visit other players' islands
    default: true

  skyblock.hub:
    description: Teleport to hub
    default: true

  skyblock.coop:
    description: Access co-op features
    default: true

  skyblock.garden:
    description: Access garden features
    default: true

  # Phase 2 Permissions
  skyblock.pets:
    description: Access pet system
    default: true
